export const SEARCH_FOUCUS = 'header/search_foucus'
export const SEARCH_BLUR = 'header/search_blur'
export const CHNAGE_LIST = 'header/change_list'
export const MOUSEENTER = 'header/MOUSEENTER'
export const MOUSELEAVE = 'header/MOUSELEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'